version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
    - inception
    build: requirement/mariadb
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    build: requirement/nginx
    env_file: .env
    ports:
    - "443:443"
    # restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    build: ./requirement/wordpress
    depends_on:
    - mariadb
    # restart: on-failure
volumes:
      wordpress:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: '/home/omahdiou/data/wordpress'
      mariadb:
        driver: local
        driver_opts:
          type: 'none' 
          o: 'bind'
          device: '/home/omahdiou/data/mariadb'

networks:
      inception:
        driver: bridge